name: Release to GiveWP.com

on:
    release:
        types: [ released ]

jobs:
    build:
        uses: impress-org/givewp-github-actions/.github/workflows/givewp-release.yml@master
        with:
            plugin_slug: give-paystack-gateway
            zip_name: give-paystack-gateway
        secrets: inherit
